[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
[rpc_endpoints]
garnet = "${GARNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
